.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. dynamiccoin_qt test_dynamiccoin_qt
clean: FORCE
	$(MAKE) -C .. dynamiccoin_qt_clean test_dynamiccoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_dynamiccoin_qt_check
dynamiccoin-qt dynamiccoin-qt.exe: FORCE
	 $(MAKE) -C .. dynamiccoin_qt
