#!/bin/bash

# This is a thin wrapper around dynamiccoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using dynamiccoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_DYNAMICCOIND

# Grab the value of $REAL_DYNAMICCOINCLI which may be dynamiccoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_DYNAMICCOINCLI}" "$@" | sed 's/\r//'
